---
- name: Get local weather info
  hosts: localhost
  connection: local
  tasks:
    - weather:
        latitude: 35.7804
        longitude: -78.6391 
        api_key: "7f7bbf445ea4401fe20e962cec3c1cd1"
